//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocArcService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public string FileId { get; set; }
        public string Container { get; set; }
        public string UserId { get; set; }
        public string OriginalFileName { get; set; }
        public string OriginalFileType { get; set; }
        public int FileSizeInKB { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
