//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocArcService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserId { get; set; }
        public string ProviderUserName { get; set; }
        public string Container { get; set; }
        public string Email { get; set; }
    }
}
